
title: My Resume
url: 'http://junlulocky.com'
baseurl: 'KiteRainCastle.github.io' #change it according to your repository name



# Profile information
yourname: 성연우  ## put your name
title: '웹 개발자'  ## your title
location: 경기도 의정부시


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
